Store config to under ~/.config in UNIX

diff --git a/package/unix/bin/ewscli b/package/unix/bin/ewscli
--- a/package/unix/bin/ewscli
+++ b/package/unix/bin/ewscli
@@ -25,24 +25,30 @@ die () {
 
 # Attempt to set APP_HOME
 # Resolve links: $0 may be a link
-THIS_DIR="$(cd "$(dirname "$0")" && pwd)"
+PRG="$0"
 APP_NAME="ewscli"
 # Follow "XDG Base Directory" in *NIX
 APP_LOCAL="$HOME/.config/$APP_NAME"
 SAVED="$(pwd)"
-if [ ! -e "$APP_LOCAL/bin/java" ] || [ ! -d "$APP_LOCAL" ] ;then
-  printf "%s" "$APP_NAME: Initialize the $APP_NAME (Creating $APP_LOCAL) ..." >&2
+
+if [ ! -d "$APP_LOCAL" ] ;then
   mkdir -p "$APP_LOCAL"
-  LOCAL_FILES=$(find -L "$THIS_DIR/../lib/$APP_NAME/" -maxdepth 1 -mindepth 1 2>/dev/null)
-  for f in $LOCAL_FILES ; do
-    cp -rf "$f" "$APP_LOCAL"
-  done
-  cd "$APP_LOCAL" || die "$APP_NAME: Failed to change directory to $APP_LOCAL"
-  printf "%s\n" "[DONE]" >&2
+  cd "$APP_LOCAL" || die "$APP_NAME:[ERROR] Failed to create the directory $APP_LOCAL"
 fi
-APP_HOME="$APP_LOCAL"
-cd "$APP_HOME" || die "$APP_NAME: Failed to change directory to $APP_HOME"
-cd "$SAVED" || die "$APP_NAME: Failed to change directory to $SAVED"
+
+# Need this for relative symlinks.
+while [ -h "$PRG" ] ; do
+    ls=$(ls -ld "$PRG")
+    link=$(expr "$ls" : '.*-> \(.*\)$')
+    if expr "$link" : '/.*' > /dev/null; then
+        PRG="$link"
+    else
+        PRG=$(dirname "$PRG")"/$link"
+    fi
+done
+cd "$(dirname "$PRG")/../" >/dev/null || die "$APP_NAME:[ERROR] Check directory"
+APP_HOME="$(pwd -P)"
+cd "$SAVED" >/dev/null || die "$APP_NAME:[ERROR] Check directory"
 
 # Add default JVM options here. You can also use JAVA_OPTS and EWSCLI_OPTS to pass JVM options to this script.
 DEFAULT_JVM_OPTS=""
@@ -66,8 +72,8 @@ case "$(uname)" in
     ;;
 esac
 
-CLASSPATH="$APP_HOME/lib/*"
-JAVA_HOME="$APP_HOME"
+JAVA_HOME="$APP_HOME/lib/$APP_NAME"
+CLASSPATH="$JAVA_HOME/lib/*"
 JAVACMD="$JAVA_HOME/bin/java"
 
 # Increase the maximum file descriptors if we can.
@@ -86,11 +92,6 @@ if [ "$cygwin" = "false" ] && [ "$darwin" = "false" ] && [ "$nonstop" = "false" 
     else
         warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
     fi
-fi
-
-# For Darwin, add options to specify how the application appears in the dock
-if $darwin; then
-    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
 fi
 
 APP_ARGS=$(save ${1+"$@"})
